#!/bin/sh

git pull origin master && \
git submodule init && \
git submodule sync && \
git submodule update && \
git submodule foreach git fetch && \
git submodule foreach git reset --hard origin/master
