#!/bin/bash

set -e

LOG=/home/$USER/activity.log

append_log() {
	echo "$(date --rfc-3339=seconds) $1" >> $LOG
}

parse_log() {
	while true; do
		read X;
		if echo $X | grep "boolean true" &> /dev/null; then
			append_log LOCKED
		elif echo $X | grep "boolean false" &> /dev/null; then
			append_log UNLOCKED
		fi
	done
}

touch $LOG
#dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | parse_log
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver',member='ActiveChanged'" | parse_log
