#!/bin/bash

# gpg --full-gen-key
# vi ~/.${account}-pass
# gpg --recipient ${key_id} --encrypt ~/.${account}-pass
# shred ~/.${account}-pass
# rm ~/.${account}-pass
# gpg -dq ~/.${1}-pass.gpg

if [ "$1" = "-n" ]; then
	shift
	cat ~/.pwd-${1} | tr -d "\n"
else
	cat ~/.pwd-${1}
fi
