#!/bin/bash

# gpg --full-gen-key
# vi ~/.${account}-pass
# gpg --recipient ${key_id} --encrypt ~/.${account}-pass
# shred ~/.${account}-pass
# rm ~/.${account}-pass
# gpg -dq ~/.${1}-pass.gpg

cat ~/.${1}-pass | tr -d "\n"
