#!/bin/bash

[ -n "$1" ] || { echo "Provide profile name!"; exit 1; }
path=$HOME/mail/$1
[ -e "$path" ] || { echo "Profile $path doesn't exist!"; exit 1; }

files=".imapfilter.lua .msmtprc .offlineimaprc .muttrc"

for f in $files; do
	ln -sf $path/$f ~/$f
done
