[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 18
normal.family = "CommitMono Nerd Font"
normal.style = "Regular"
bold.family = "CommitMono Nerd Font"
bold.style = "Bold"
italic.family = "CommitMono Nerd Font"
italic.style = "Italic"

[bell]
duration = 0

[keyboard]
bindings = [
   { key = "C", mods = "Control|Shift", action = "Copy" },
   { key = "V", mods = "Control|Shift", action = "Paste" },
]

[mouse]
bindings = [
	{ mouse = "Middle", action = "PasteSelection" },
]

[terminal]
osc52 =  "CopyPaste"
