theme = "base16_default"

[editor]
mouse = false
soft-wrap.enable = true
auto-pairs = false
# TODO: flip this to false eventually?
auto-info = true
indent-heuristic = "hybrid"
line-number = "relative"

# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"

"%" = "match_brackets"

V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

j = "move_line_down"
k = "move_line_up"
g = { "j" = "move_visual_line_down", "k" =  "move_visual_line_up" }
