NAME:=neomutt
GIT:=https://github.com/neomutt/neomutt.git

include Makefile.lib

CONFIGURE_FLAGS+= --disable-gpgme
CONFIGURE_FLAGS+= --disable-doc
CONFIGURE_FLAGS+= --gnutls
CONFIGURE_FLAGS+= --gss
CONFIGURE_FLAGS+= --idn
CONFIGURE_FLAGS+= --mixmaster
CONFIGURE_FLAGS+= --sasl
CONFIGURE_FLAGS+= --ssl

build:
	$(SUBMAKE) build_autoconf
