#!/bin/bash

set -e

__usage() {
	echo "usage: mk <recipe>"
	echo "       mk <recipe> clean"
	exit 1
}

R="$HOME/opt"
STAMP="$R/stamp"
SRC="$R/src"
PREFIX="$R/sysroot"

FILE="$1"
PKG="$(basename "$FILE")"
[ -z "$FILE" ] && __usage
shift
if [ ! -z "$1" ]; then
	CMD="$1"
	shift
fi

S="$SRC/$PKG"
B="$R/build/$PKG"
PKG_STAMP_FETCH="$STAMP/${PKG}_fetch"
PKG_STAMP_BUILD="$STAMP/${PKG}_build"

# PACKAGES CAN CONFIGURE THESE
# {{{
configure_flags=(--prefix=$PREFIX)
make_flags=()
cmake_flags=()
install_flags=()
invoke_install=true

pre_build() { :; }
post_build() { :; }
# }}}

MAX_NPROC=64
NPROC=$(nproc)
NPROC=$(echo "if(${NPROC}>${MAX_NPROC}){${MAX_NPROC}}else{${NPROC}}" | bc)
export CMAKE_BUILD_PARALLEL_LEVEL=$NPROC

say() { echo "${PKG}: $@"; }
die() { echo "${PKG}: $@"; exit 1; }

[ -z "$PKG" ] && { die "Specify package name!"; }

say "NPROC=$NPROC PREFIX=$PREFIX"

__fetch_git() {
	local s="$1"
	local dirname="$2"

	if [ -d "$dirname" ]; then
		(cd $dirname && git pull --ff-only)
	else
		git clone $s $dirname
	fi

	(cd $dirname && git describe --always) >> $PKG_STAMP_FETCH

	if [ ! -e "$PKG" ]; then
		ln -s $dirname $PKG
	fi
}

__fetch_tar() {
	local s="$1"

	if [ ! -e "$(basename $s)" ]; then
		say "fetching $s into $PWD"
		curl -LO "$s"
		say "extracting $s into $S"
		mkdir -p "$S"
		tar xf "$(basename $s)" -C "$S"
	fi

	echo "$s" >> $PKG_STAMP_FETCH
}

fetch() {
	rm -f $PKG_STAMP_FETCH

	if [ -e "$source" ]; then
		die "No source specified!"
	fi

	for s in ${source[@]}; do
		local fullname="$(basename $s)"
		local extension="${fullname##*.}"
		local dirname="${fullname%.*}"

		case "$extension" in
			git) __fetch_git "$s" "$dirname" ;;
			*) __fetch_tar "$s" ;;
		esac
	done
}

__build_cmake() {
	cmake -DCMAKE_INSTALL_PREFIX=$PREFIX ${cmake_flags[@]} "$S"
	cmake --build .
	cmake ${install_flags[@]} \
		-DCMAKE_INSTALL_PREFIX=$PREFIX \
		-P cmake_install.cmake
}

__build_autoconf() {
	[ -x "$S/autogen.sh" ] && (cd "$S" && ./autogen.sh) || :
	$S/configure --prefix=$PREFIX ${configure_flags[@]}
	make -j$NPROC ${make_flags[@]}
	[ "$invoke_install" = " true" ] && make ${install_flags[@]} install
}

__build_make() {
	make_flags+=(PREFIX=$PREFIX)
	install_flags+=(PREFIX=$PREFIX)

	make -j$NPROC ${make_flags[@]}
	[ "$invoke_install" = " true" ] && make ${install_flags[@]} install
}

extract_to_prefix() {
	for s in ${source[@]}; do
		(cd $PREFIX && tar xf $SRC/$(basename $s))
	done
}

build() {
	if [ -f "$S/CMakeLists.txt" ]; then
		__build_cmake
	elif [ -f "$S/configure" -o -f "$S/configure.ac" ]; then
		# build in the source tree
		B="$S"
		cd "$B"

		__build_autoconf
	elif [ -f "$S/Makefile" ]; then
		# build in the source tree
		B="$S"
		cd "$B"

		__build_make
	else
		die "Unsupported build system!"
	fi
}

[ ! -e "$FILE" ] && {
	echo "File '$FILE' not found"
	exit 1
} || source "$FILE"

checksum() {
	sha256sum "$1" 2>&1 | cut -d' ' -f1
}

checksum_matches() {
	test "$(checksum "$1")" = "$(checksum "$2")"
}

__clean() {
	say "clean"

	(cd $SRC && for s in ${source[@]}; do rm -f $(basename $s); done)

	rm -f  $PKG_STAMP_FETCH $PKG_STAMP_BUILD
	rm -rf $B $S
}

__build() {
	mkdir -p "$SRC" "$STAMP" "$PREFIX/bin"

	say "fetch"
	(cd $SRC && fetch)

	if checksum_matches "$PKG_STAMP_FETCH" "$PKG_STAMP_BUILD"; then
		say "build is up to date"
		say "run '$0 $FILE clean' to force rebuild"
		exit 0
	fi

	say "pre build"
	[ -e "$S" ] && (cd $S && pre_build)
	say "build"
	rm -rf "$B"
	mkdir -p "$B"
	(cd $B && build)
	say "post build"
	(cd $B && post_build)

	cp "$PKG_STAMP_FETCH" "$PKG_STAMP_BUILD"
}

case "$CMD" in
	clean) __clean ;;
	help) __usage ;;
	*) __build ;;
esac
